language: ruby
rvm:
  - 2.7
gemfile:
  - Gemfile
bundler_args:
cache: bundler
before_install:
  - sudo apt-get install rrdtool librrd-dev sqlite3 libsqlite3-dev
  - gem install -v "2.1.4" bundler
  - bundle config set path vendor/bundle
before_script:
  - bundle exec focuslight init
