language: ruby
rvm:
  - 2.5
gemfile:
  - Gemfile
bundler_args: --deployment
cache: bundler
before_install:
  - sudo apt-get install rrdtool librrd-dev sqlite3 libsqlite3-dev
  - gem update --system
  - gem install -v "1.17.3" bundler
before_script:
  - bundle exec focuslight init
